### ISSUE TITLE
Error while fetching extension info

### ISSUE THREAD

**Issue by LiaraAlis** [FriendsOfShopware/shopware-cli#146]
### Question

While fetching extension info I get the following error:
```
2023-03-13T12:53:16.338+0100    DEBUG   Using token cache from /home/pankow/.cache/shopware-api-client-token.json
2023-03-13T12:53:16.338+0100    DEBUG   Impersonating currently as blackpoint GmbH (15387)
2023-03-13T12:53:16.610+0100    DEBUG   GET: https://api.shopware.com/companies/15387/allocations
2023-03-13T12:53:16.922+0100    DEBUG   GET: https://api.shopware.com/plugins?producerId=88&search=BpaPlatformVideoIframeCookieHandler
2023-03-13T12:53:17.009+0100    DEBUG   GET: https://api.shopware.com/plugins/13552
2023-03-13T12:53:17.365+0100    DEBUG   GET: https://api.shopware.com/plugins/13552/pictures
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc43c59]

goroutine 1 [running]:
github.com/FriendsOfShopware/shopware-cli/cmd/account.glob..func11(0x182ba20, {0xc00031ca60?, 0x1?, 0x1?})
        github.com/FriendsOfShopware/shopware-cli/cmd/account/account_producer_extension_info_pull.go:158 +0x1599
github.com/spf13/cobra.(*Command).execute(0x182ba20, {0xc00031ca30, 0x1, 0x1})
        github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x182a040)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.6.1/command.go:961
github.com/FriendsOfShopware/shopware-cli/cmd.Execute({0x123c8b8?, 0xc000453da0})
        github.com/FriendsOfShopware/shopware-cli/cmd/root.go:27 +0x65
main.main()
        github.com/FriendsOfShopware/shopware-cli/main.go:12 +0x4a

```

Have I done something wrong or could this be a bug?

**Comment by shyim** [comment]
Looks like a bug.
Can you invite me temporary to the company? s.sayakci@shopware.com

**Comment by LiaraAlis** [comment]
@shyim Invitation sent. I hope the permissions are sufficient.
