### ISSUE TITLE
Zipping extension fails with error "digital envelope routines unsuported" when using wrong? node version.

### ISSUE THREAD

**Issue by element-code** [FriendsOfShopware/shopware-cli#196]
### PHP Version

^8.1

### Shopware Version

^6.4.0

### Actual behaviour

Zipping extension complains about wrong node version and fails later (node:internal/crypto/hash:71 Error: error:0308010C:digital envelope routines::unsupported)

```
Using docker image sha256:56081d1f3e222d8afef16c273d513cd8cd2f4a16d0ff27fe2ac9e96f226a1a22 for ghcr.io/friendsofshopware/shopware-cli:latest with digest ghcr.io/friendsofshopware/shopware-cli@sha256:4b7b56b1c0f7485e76088a6da85c74a1b7ece3c03d0a918bbf1db86a436243c9 ...
$ shopware-cli --version
shopware-cli version 0.1.78
$ shopware-cli extension zip ./ package --disable-git --release --verbose
[...]
2023-06-05T11:36:18.058Z	INFO	Cloning shopware with branch: 6.4 into /tmp/extension1960153158
Cloning into '/tmp/extension1960153158'...
Updating files: 100% (18823/18823), done.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'administration@1.0.0',
npm WARN EBADENGINE   required: { node: '^16.0.0', npm: '^8.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@shopware-ag/jest-preset-sw6-admin@4.0.0',
npm WARN EBADENGINE   required: { node: '^16.0.0', npm: '^8.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.5.1' }
npm WARN EBADENGINE }
[...]
> administration@1.0.0 build
> mode=production webpack
@Deprecated: You are using an incompatible Node.js version. Supported version range: ^16.0.0
# Compiling with Webpack configuration
# Production mode is activated 🚀
# Plugin "FooBar": Injected successfully
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/tmp/extension1960153158/src/Administration/Resources/app/administration/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/extension1960153158/src/Administration/Resources/app/administration/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/extension1960153158/src/Administration/Resources/app/administration/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/extension1960153158/src/Administration/Resources/app/administration/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/extension1960153158/src/Administration/Resources/app/administration/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/extension1960153158/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/extension1960153158/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/extension1960153158/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/extension1960153158/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/tmp/extension1960153158/src/Administration/Resources/app/administration/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /tmp/extension1960153158/src/Administration/Resources/app/administration/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Node.js v18.16.0
```

How to solve this?

### Expected behaviour

Plugin builds successfully

### Steps to Reproduce?

Running latest docker image

**Comment by shyim** [comment]
Set NODE_VERSION=16 as environment variable for the container

**Comment by element-code** [comment]
Chaning the requirements to SW ^6.5 and PHP ^8.2 fixes this issue as well, thx!
